#!python3
from paws.arg_paw import ArgPaw
from paws.util_paw import UtilPaw
from paws.scan_paw import ScanPaw

# execute mode with given options (threading/multipr., how many th, target, add. ports...)


class Kitten:

    arg_paw = None
    util_paw = None
    scan_paw = None

    options = {}

    def __init__(self) -> None:
        self.arg_paw = ArgPaw()

        self.options = self.arg_paw.get_options()
        
        self.util_paw = UtilPaw(self.options)
        self.scan_paw = ScanPaw(self.options, self.util_paw)

        self.util_paw.print_prolog()

def main():
    try:
        Kitten()
    except KeyboardInterrupt:
        print('\033[1m\nmeow.\033[0m')

if __name__ == '__main__':
    main()