#!/usr/bin/python3
import argparse
from paws.util_paw import UtilPaw
from paws.scan_paw import ScanPaw

Parser = argparse.ArgumentParser(description='Process some integers.')
Parser.add_argument(
                    '-t', '--target',
                    type=str,
                    help='Define the target that is to be scanned.'
)
Parser.add_argument('-v', '--verbose',
                    action='store_true',
                    help='Run verbosely.'
)
Parser.add_argument('-pr', '--portrange',
                    type=int,
                    help='Define the port range that is to be scanned.'
)

class Kitten():

    util_paw = None
    scan_paw = None

    options = {
        'target': 'localhost',
        'portrange': 65535,
        'verbose': False,
    }

    def __init__(self) -> None:
        self.options = self.get_parsed_args()
        self.util_paw = UtilPaw(self.options)
        self.scan_paw = ScanPaw(self.options, self.util_paw)

        print(self.scan_paw.get_open_ports())


    def get_parsed_args(self) -> dict:

        new_options = self.options
        args = Parser.parse_args().__dict__

        for key in args.keys():
            if args[key] != None:
                new_options[key] = args[key]

        return new_options


if __name__ == '__main__':
    try:
        Kitten()
    except KeyboardInterrupt:
        print('\033[1m meow.\033[0m')